#!/usr/bin/env python3
"""Render a BOM's managed dependencies as a scannable pom.

A Bill of Materials declares no dependencies of its own: every coordinate lives
inside <dependencyManagement>, which states "if you use this, use this version"
rather than "this is used". Vulnerability scanners that read pom.xml therefore
find nothing to scan here, and report success over a file whose entire purpose
is choosing versions for the rest of the ecosystem.

This script reprojects those managed entries into ordinary <dependencies>, with
properties resolved, so a scanner sees concrete coordinate-plus-version facts.
The output is a scanning artefact and is never published or built against.
"""
import sys
import xml.etree.ElementTree as ET

POM_NS = "http://maven.apache.org/POM/4.0.0"
NS = {"m": POM_NS}

# Artifacts published by this project rather than by a third party. They are excluded because
# a scanner resolves each coordinate against public repositories, and these are not there: the
# lookups fail, and in bulk they earn an HTTP 429 that aborts the whole scan. Nothing is lost by
# skipping them, since a public advisory database holds no advisories for private artifacts --
# the code inside them is scanned in its own repository, which is where it can actually be fixed.
FIRST_PARTY_GROUP_PREFIX = "xyz.tcheeric"

TEMPLATE = """<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <groupId>xyz.tcheeric.scan</groupId>
  <artifactId>bom-managed-dependencies</artifactId>
  <version>0</version>
  <!-- Generated by scripts/managed-deps-to-pom.py. Do not commit or deploy. -->
  <dependencies>
{dependencies}  </dependencies>
</project>
"""


def resolve(value, properties):
    """Expand ${...} property references, tolerating one level of indirection."""
    for _ in range(5):
        if "${" not in value:
            break
        start = value.index("${")
        end = value.index("}", start)
        name = value[start + 2:end]
        if name not in properties:
            return None
        value = value[:start] + properties[name] + value[end + 1:]
    return None if "${" in value else value


def read_properties(root):
    node = root.find("m:properties", NS)
    if node is None:
        return {}
    return {child.tag.split("}")[-1]: (child.text or "").strip()
            for child in node}


def managed_dependencies(root, properties):
    path = "m:dependencyManagement/m:dependencies/m:dependency"
    for dependency in root.findall(path, NS):
        version = dependency.findtext("m:version", default="", namespaces=NS)
        resolved = resolve(version.strip(), properties) if version else None
        if not resolved:
            continue
        # A BOM import contributes no artifact of its own to scan; its contents
        # are managed by whichever project imports it.
        if dependency.findtext("m:scope", default="", namespaces=NS) == "import":
            continue
        group = dependency.findtext("m:groupId", default="", namespaces=NS).strip()
        if group.startswith(FIRST_PARTY_GROUP_PREFIX):
            continue
        yield (group,
               dependency.findtext("m:artifactId", default="", namespaces=NS).strip(),
               resolved)


def main():
    source, destination = sys.argv[1], sys.argv[2]
    root = ET.parse(source).getroot()
    properties = read_properties(root)

    rendered = "".join(
        f"    <dependency>\n"
        f"      <groupId>{group}</groupId>\n"
        f"      <artifactId>{artifact}</artifactId>\n"
        f"      <version>{version}</version>\n"
        f"    </dependency>\n"
        for group, artifact, version in managed_dependencies(root, properties))

    if not rendered:
        sys.exit(f"error: no managed dependencies resolved from {source}; "
                 "refusing to emit an empty pom that would scan clean")

    with open(destination, "w") as handle:
        handle.write(TEMPLATE.format(dependencies=rendered))
    print(f"{rendered.count('<dependency>')} managed dependencies written to {destination}")


if __name__ == "__main__":
    main()
