#!/usr/bin/env python3
"""Render a BOM's managed dependencies as a scannable pom.

A Bill of Materials declares no dependencies of its own: every coordinate lives
inside <dependencyManagement>, which states "if you use this, use this version"
rather than "this is used". Vulnerability scanners that read pom.xml therefore
find nothing to scan here, and report success over a file whose entire purpose
is choosing versions for the rest of the ecosystem.

This script reprojects those managed entries into ordinary <dependencies>, with
properties resolved, so a scanner sees concrete coordinate-plus-version facts.
The output is a scanning artefact and is never published or built against.
"""
import sys
import xml.etree.ElementTree as ET
from xml.sax.saxutils import escape

POM_NS = "http://maven.apache.org/POM/4.0.0"
NS = {"m": POM_NS}

# Artifacts published by this project rather than by a third party. They are excluded because
# a scanner resolves each coordinate against public repositories, and these are not there: the
# lookups fail, and in bulk they earn an HTTP 429 that aborts the whole scan. Nothing is lost by
# skipping them, since a public advisory database holds no advisories for private artifacts --
# the code inside them is scanned in its own repository, which is where it can actually be fixed.
FIRST_PARTY_GROUP_PREFIX = "xyz.tcheeric"

# Bound on ${a} -> ${b} -> value chains. Maven allows arbitrary nesting, but a cycle would
# otherwise loop forever, and no real BOM nests this deeply.
MAX_PROPERTY_EXPANSIONS = 5

TEMPLATE = """<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <groupId>xyz.tcheeric.scan</groupId>
  <artifactId>bom-managed-dependencies</artifactId>
  <version>0</version>
  <!-- Generated by scripts/managed-deps-to-pom.py. Do not commit or deploy. -->
  <dependencies>
{dependencies}  </dependencies>
</project>
"""

USAGE = "usage: managed-deps-to-pom.py <source-pom> <destination-pom>"


class UnresolvedVersionError(Exception):
    """A managed version could not be reduced to a literal.

    Raised rather than returning a sentinel because the caller must not be able
    to ignore it by accident: a dependency dropped here is a dependency the
    vulnerability scan will never see, which is the precise failure this whole
    script exists to prevent.
    """


def resolve(value, properties):
    """Expand ${...} property references into a literal version."""
    for _ in range(MAX_PROPERTY_EXPANSIONS):
        if "${" not in value:
            return value
        start = value.index("${")
        end = value.find("}", start)
        if end == -1:
            raise UnresolvedVersionError(f"malformed property reference in {value!r}")
        name = value[start + 2:end]
        if name not in properties:
            raise UnresolvedVersionError(f"no property {name!r} for {value!r}")
        value = value[:start] + properties[name] + value[end + 1:]
    raise UnresolvedVersionError(
        f"{value!r} still unresolved after {MAX_PROPERTY_EXPANSIONS} expansions")


def read_properties(root):
    node = root.find("m:properties", NS)
    if node is None:
        return {}
    return {child.tag.split("}")[-1]: (child.text or "").strip()
            for child in node}


def is_scannable(dependency):
    """Whether this managed entry maps to a third-party artifact worth scanning."""
    # A BOM import contributes no artifact of its own; its contents are managed
    # by whichever project imports it.
    if dependency.findtext("m:scope", default="", namespaces=NS) == "import":
        return False
    group = dependency.findtext("m:groupId", default="", namespaces=NS).strip()
    return not group.startswith(FIRST_PARTY_GROUP_PREFIX)


def managed_dependencies(root, properties):
    """Yield (group, artifact, version) for every scannable managed entry.

    Raises UnresolvedVersionError if a scannable entry has no usable version, so
    that a coordinate can never disappear from the scan unnoticed.
    """
    path = "m:dependencyManagement/m:dependencies/m:dependency"
    for dependency in root.findall(path, NS):
        if not is_scannable(dependency):
            continue
        group = dependency.findtext("m:groupId", default="", namespaces=NS).strip()
        artifact = dependency.findtext("m:artifactId", default="", namespaces=NS).strip()
        version = dependency.findtext("m:version", default="", namespaces=NS).strip()
        if not version:
            raise UnresolvedVersionError(f"{group}:{artifact} declares no version")
        try:
            yield group, artifact, resolve(version, properties)
        except UnresolvedVersionError as error:
            raise UnresolvedVersionError(f"{group}:{artifact}: {error}") from error


def render(root, properties):
    return "".join(
        f"    <dependency>\n"
        f"      <groupId>{escape(group)}</groupId>\n"
        f"      <artifactId>{escape(artifact)}</artifactId>\n"
        f"      <version>{escape(version)}</version>\n"
        f"    </dependency>\n"
        for group, artifact, version in managed_dependencies(root, properties))


def main():
    if len(sys.argv) != 3:
        sys.exit(USAGE)
    source, destination = sys.argv[1], sys.argv[2]

    try:
        root = ET.parse(source).getroot()
    except (OSError, ET.ParseError) as error:
        sys.exit(f"error: cannot read {source}: {error}")

    try:
        dependencies = render(root, read_properties(root))
    except UnresolvedVersionError as error:
        sys.exit(f"error: {error}\n"
                 "A dependency that cannot be resolved would be missing from the "
                 "vulnerability scan, so this is fatal rather than skipped.")

    if not dependencies:
        sys.exit(f"error: no managed dependencies resolved from {source}; "
                 "refusing to emit an empty pom that would scan clean")

    try:
        with open(destination, "w") as handle:
            handle.write(TEMPLATE.format(dependencies=dependencies))
    except OSError as error:
        sys.exit(f"error: cannot write {destination}: {error}")

    print(f"{dependencies.count('<dependency>')} managed dependencies "
          f"written to {destination}")


if __name__ == "__main__":
    main()
